apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-sources-volume
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi #Size of the volume
  accessModes:
    - ReadWriteOnce #type of access
  hostPath:
    path: "/Users/jason/Development/Kubernetes/vagrant/pv" #host location.  take a look at the VM with the k8s master and check which volume is mounted